### ISSUE TITLE
FATAL_ERROR "No OpenCV 3 or 4 detected."

### ISSUE THREAD

**Issue by pedropro** [jpl-x/x_vio_ros#1]
This error shows up during compilation even if you have Opencv 3.

### Cause:
This sequence in [https://github.com/jpl-x/x_vio_ros/blob/master/CMakeLists.txt](https://github.com/jpl-x/x_vio_ros/blob/master/CMakeLists.txt)
```
find_package(OpenCV 3 QUIET)
find_package(OpenCV 4 QUIET)
```
Overwrites the Flag `OpenCV_FOUND` with 0 if you don't have OpenCV 4
leading to 
```
message(FATAL_ERROR "No OpenCV 3 or 4 detected.")
```
### Solution A:
Ignore version
```
find_package(OpenCV QUIET)
```
### Solution B:
Check/Use only OpenCV 4 if OpenCV 3 is missing.
```
find_package(OpenCV 3 QUIET)

if(opencv3_catkin_FOUND)
  message("OpenCV3_catkin detected")
  set(OPENCV_PACKAGE "opencv3_catkin")
  set(OpenCV_INCLUDE_DIRS "")
  set(OpenCV_LIBRARIES "")
elseif(OpenCV_FOUND)
  message("OpenCV system install detected")
  set(OPENCV_PACKAGE "")
else()
    find_package(OpenCV 4 REQUIRED)
    if(OpenCV_FOUND)
        message("OpenCV system install detected")
        set(OPENCV_PACKAGE "")
    else()
        message(FATAL_ERROR "No OpenCV 3 or 4 detected.")
    endif()
endif()
```

**Comment by jeff-delaune** [comment]
Thank you Pedro. A fix was implemented in the branch "hotfix-opencv-cmake" of the x_vio_ros and x repos. Can you confirm that it solves the issue on your side?

**Comment by pedropro** [comment]
I confirm. It works.

**Comment by jeff-delaune** [comment]
Thanks. The fix got merged into the master branch of both repos.
